config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/searches' => 'searches#search'


  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy,]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user


  attachment :profile_image

  validates :name, uniqueness: true ,length: { minimum: 2, maximum: 20 }
  validates :introduction , length: { maximum: 50 }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
     redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
     render :edit
    end
  end

   private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0  mx-auto">

<h2>User info</h2>

<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model:@user, local:true do |f| %>

  <div class="form-group">
  <div>
  <label for="inputName">Name</label>
  </div>
  <%= f.text_field :name, autofocus: true, id:"inputName" %>
  </div>

<div class="form-group">
  <div>
  <label for="inputImage">ProfileImage</label>
  </div>
  <%= f.attachment_field :profile_image, placeholder: "Image" %>
</div>

<div class"form-group">
  <div>
  <label for="inputIntroduction">Introduction</label>
  </div>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction" %>
</div>

<div class="form-group">
  <%= f.submit "Update User" , class: 'btn btn-secondary' %>
</div>

<% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class='col-md-3'>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">

 <h2>Users</h2>
  <table class="table table-hover table-invers">
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
　　　　<% @users.each do |user| %>
            <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, fallback: "no_image.png",size: "30x30" %></td>
                <td><%= user.name %></td>
                <td><%= render 'relationships/follow_button', user: user %></td>
                <td><%= link_to "Show", user_path(user) %></td>
            </tr>
        <% end %>
    </tbody>
  </table>


    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">

     <h2>User info</h2>
     <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.png",size: "70x70" %>
     <table class="table">
       <tr>
        <th>name</th>
        <th><%= @user.name %></th>
       </tr>
       <tr>
         <th>introduction</th>
         <th><%= @user.introduction %></th>
       </tr>
       <tr>
        <th>follows</th>
        <th><%= link_to " #{@user.followings.count} ", user_followings_path(@user.id) %></th>
       </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to " #{@user.followers.count} ", user_followers_path(@user.id) %></th>
      </tr>
      <tr>
        <th>
    <% if @user == current_user %>
      <%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
    <% elsif current_user.following?(@user) %>
      <%= link_to "Unfollow", user_relationships_path(@user.id), method: :delete %>
    <% else %>
      <%= link_to "Follow", user_relationships_path(@user.id), method: :post %>
    <% end %>
        </th>
      </tr>
     </table>






         <h1>New book</h1>
     <%= form_with model: @book, local:true do |f| %>
       <h4>Title</h4>
       <%= f.text_field :title %>
      <h4>opinion</h4>
      <%= f.text_area :body %></br>
      <%= f.submit 'Create Book' %>
       <% end %>

    </div>


    <div class="col-md-8 offset-md-1">

     <table class="table table-hover table-invers">
       <h2>Book</h2>
    <thead>
        <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
　　　　<% @books.each do |book| %>
            <tr>

                <td>
                    <%= link_to user_path(@user) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.png",size: "30x30" %>
                    <% end %>
                </td>
                <td><%= link_to book.title, "/books/#{book.id}" %></td>
                <td><%= book.body %></td>
                 <% if @user.id == current_user.id %>
                <td><%= link_to "Edit", edit_book_path(book) %></td>
                <% else %>
                <% end %>
                <td><%= link_to "コメント数: #{book.book_comments.count} ", book_path(book.id) %></td>

            </tr>
        <% end %>
    </tbody>
  </table>


    </div>
  </div>
</div>