config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/searches' => 'searches#search'


  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy,]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end


end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true,  length: { maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController



  def create
    @books = Book.all
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
    else
      render :index
    end
  end

  def index
     @books = Book.all
     @user = current_user
     @book = Book.new
    @all_ranks = Book.find(Favorite.group(:book_id).order('count(book_id) desc').limit(5).pluck(:book_id))
  end

  def show
     @book_new = Book.new
     @book = Book.find(params[:id])
     @user = @book.user
     @books = Book.all
     @book_comment = BookComment.new
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def edit
    @book = Book.find(params[:id])
     unless @book.user == current_user
     redirect_to books_path
     end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
    <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 70, 70, fallback: "no_image.png",size: "70x70" %>
    <table class="table">
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
        <tr>
        <th>follows</th>
        <th><%= link_to " #{@user.followings.count} ", user_followings_path(@user.id) %></th>
        </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to " #{@user.followers.count} ", user_followers_path(@user.id) %></th>
      </tr>

      <tr>
        <th>
    <% if @user == current_user %>
      <%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
    <% elsif current_user.following?(@user) %>
      <%= link_to "Unfollow", user_relationships_path(@user.id), method: :delete %>
    <% else %>
      <%= link_to "Follow", user_relationships_path(@user.id), method: :post %>
    <% end %>
        </th>
      </tr>
    </table>

    <h1>New book</h1>
    <%= form_with model:book, local:true do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      <h4>opinion</h4>
      <%= f.text_area :body %></br>
      <%= f.submit 'Create Book' %>
    <% end %>

app/views/books/_comments.html.erb
<% book.book_comments.each do |book_comment| %>

　　　      <tr>
      　　　    <td>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.png",size: "30x30" %><br>
                  <%= link_to book_comment.user.name, user_path(user) %>
      　　　    </td>
      　　　    <td>
                  <%= book_comment.comment %>
      　　　    </td>
      　　　    <td>
      　　　      <% if book_comment.user == current_user %>
                  <div class="comment-delete">
                  <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class:'btn btn-danger', remote: true %>
                  </div>
                  <% end %>
      　　　    </td>
  　　　       </tr>

         <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0  mx-auto">

<h2>Editing Book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model:@book, local:true do |f| %>

  <div class="form-group">
  <div>
  <label for="inputTitle">Title</label>
  </div>
  <%= f.text_field :title, autofocus: true, id:"inputBook" %>
  </div>

<div class"form-group">
  <div>
  <label for="inputOpinion">Opinion</label>
  </div>
  <%= f.text_field :body, autofocus: true, id:"inputBody" %>
</div>

<div class="form-group">
  <%= f.submit "Update Book" , class: 'btn btn-success' %>
</div>

<% end %>
<%= link_to "Show", book_path %> |
<%= link_to "Back", books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
    <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class='col-md-3'>
  <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">

 <h2>Books</h2>
  <table class="table table-hover table-invers">
    <thead>
        <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
　　　　<% @all_ranks.each.with_index(1) do |book, i| %>
            <tr>

                <td>
                    <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.png",size: "30x30" %>
                    <% end %>
                </td>
                <td><%= link_to book.title, "/books/#{book.id}" %></td>
                <td><%= book.body %></td>
                <td>
                  <div id="favorites_buttons_<%= book.id %>">
                    <%= render partial: 'favorites/favorite-btn', locals: { book: book} %>
                  </div>
                </td>
                <td><%= link_to "コメント数: #{book.book_comments.count} ", book_path(book.id) %></td>
            </tr>
        <% end %>
    </tbody>
  </table>


    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class='col-md-3'>
    <%= render 'books/book', book: @book_new %>
    </div>
    <div class="col-md-8 offset-md-1">

　　　<h2>Book detail</h2>
　　　<table class="table">
　　　  <tbody>
　　　    <tr id="book_<%= @book.id %>">
　　　      <td>
　　　       <%= attachment_image_tag @book.user, :profile_image, :fill, 30, 30, fallback: "no_image.png",size: "30x30" %><br>
　　　       <%= link_to @book.user.name, user_path(@user) %>
　　　      </td>
　　　      <td><%= link_to @book.title, "/books/#{@book.id}" %></td>
　　　      <td><%= @book.body %></td>
　　　      <td>
　　　        <% if @book.user == current_user %>
　　　        <%= link_to "Edit", edit_book_path(@book) ,class:'btn btn-success' %>
　 　　　     <% end %>
　 　　　   </td>
　　　      <td>
　　　        <% if @book.user == current_user %>
　　　        <%= link_to "Destroy", book_path(@book), method: :delete , class:'btn btn-danger'  %>
　　　        <% end %>
　　　      </td>
              <td>
                <div id="favorites_buttons_<%= @book.id %>">
                    <%= render partial: 'favorites/favorite-btn', locals: { book: @book} %>
                </div>
              </td>
　　　      <td class="comments-count">
　　　        コメント数：<%= @book.book_comments.count %>
　　　      </td>
　　　   </tr>

　　　  </tbody>
　　　</table>
　　　<div>
　　　  <table>
　　　    <tbody class="comments_index">
            <%= render 'books/comments', book: @book, user: @user %>
          </tbody>
　　　  </table>
　　　</div>
　　<div class="col-md-8 offset-md-1">
　　　<%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
  　　<%= f.text_area :comment, size: "80x7", rows:'5', class:"text_field" %><br>
  　　<%= f.submit "送信" %>
　　　<% end %>
　　</div>
  </div>

  </div>
</div>